# Generated by Django 4.1 on 2024-04-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_emergencycontact_nutrimentandsupply_tip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='type_of_catastrophe',
        ),
    ]
