# Generated by Django 4.1 on 2024-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_remove_emergencycontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
