# Generated by Django 4.1 on 2024-04-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='custom_user',
            new_name='user',
        ),
    ]
